// config.js - generated by exportConfigForStaticFile()
// generated at: 2025-12-04T09:14:49.020Z

// ตั้งค่า behavior ฝั่ง front-end
window.APP_SETTINGS = {
  // 'static' = ใช้ config จากไฟล์นี้เลย
  // 'api'    = ไปโหลดจาก Apps Script ?act=config
  
  configSource: 'static'
  // configSource: 'api'
};

window.STATIC_CONFIG = {
  "ok": true,
  "config": {
    "langDefault": "th",
    "sections": [
      {
        "id": "basic",
        "order": 1,
        "title": {
          "th": "ส่วนที่ 1: ข้อมูลพื้นฐานผู้ตอบ",
          "en": "Part 1: Respondent information"
        },
        "description": {
          "th": "",
          "en": ""
        },
        "questions": [
          {
            "id": "status",
            "sectionId": "basic",
            "order": 1,
            "type": "radio",
            "label": {
              "th": "สถานะของท่าน",
              "en": "Your status"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": true,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [],
            "options": [
              {
                "value": "STU",
                "order": 1,
                "label": {
                  "th": "นักศึกษา",
                  "en": "Student"
                }
              },
              {
                "value": "STAFF_BU",
                "order": 2,
                "label": {
                  "th": "บุคลากรของมหาวิทยาลัย",
                  "en": ""
                }
              },
              {
                "value": "PARENT",
                "order": 3,
                "label": {
                  "th": "ผู้ปกครอง",
                  "en": ""
                }
              },
              {
                "value": "ALUMNI",
                "order": 4,
                "label": {
                  "th": "ศิษย์เก่า",
                  "en": ""
                }
              },
              {
                "value": "EXTERNAL",
                "order": 5,
                "label": {
                  "th": "หน่วยงานภายนอก / บุคคลภายนอก",
                  "en": ""
                }
              },
              {
                "value": "OTHER",
                "order": 99,
                "label": {
                  "th": "อื่น ๆ",
                  "en": "Other"
                }
              }
            ]
          },
          {
            "id": "faculty_id",
            "sectionId": "basic",
            "order": 2,
            "type": "select",
            "label": {
              "th": "คณะ/วิทยาลัยของท่าน",
              "en": "Your faculty/school"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": true,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [
              "STU"
            ],
            "options": []
          },
          {
            "id": "program_id",
            "sectionId": "basic",
            "order": 3,
            "type": "select",
            "label": {
              "th": "หลักสูตร/สาขาวิชาที่ท่านกำลังศึกษา",
              "en": "Program/major you are enrolled in"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": true,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [
              "STU"
            ],
            "options": []
          },
          {
            "id": "unit_id",
            "sectionId": "basic",
            "order": 4,
            "type": "select",
            "label": {
              "th": "หน่วยงานที่ท่านสังกัด",
              "en": ""
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": true,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [
              "STAFF_BU"
            ],
            "options": []
          },
          {
            "id": "parent_detail",
            "sectionId": "basic",
            "order": 5,
            "type": "textarea",
            "label": {
              "th": "โปรดระบุความสัมพันธ์กับนักศึกษาหรือรายละเอียดเพิ่มเติม (ถ้าต้องการ)",
              "en": ""
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": false,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [
              "PARENT"
            ],
            "options": []
          },
          {
            "id": "alumni_detail",
            "sectionId": "basic",
            "order": 6,
            "type": "textarea",
            "label": {
              "th": "โปรดระบุรุ่น/ปีที่สำเร็จการศึกษา หรือรายละเอียดเพิ่มเติม (ถ้าต้องการ)",
              "en": ""
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": false,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [
              "ALUMNI"
            ],
            "options": []
          },
          {
            "id": "external_org",
            "sectionId": "basic",
            "order": 7,
            "type": "textarea",
            "label": {
              "th": "โปรดระบุชื่อหน่วยงาน/องค์กรของท่าน (ถ้าต้องการ)",
              "en": ""
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": false,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [
              "EXTERNAL"
            ],
            "options": []
          }
        ]
      },
      {
        "id": "quality",
        "order": 2,
        "title": {
          "th": "ส่วนที่ 2: ความสำคัญและความพึงพอใจต่อคุณภาพฯ",
          "en": "Part 2: Importance & satisfaction of quality"
        },
        "description": {
          "th": "",
          "en": ""
        },
        "questions": [
          {
            "id": "wifi_sat",
            "sectionId": "quality",
            "order": 2,
            "type": "scale",
            "label": {
              "th": "ระดับ “ความพึงพอใจ” ต่อคุณภาพการเชื่อมต่ออินเทอร์เน็ต (Wi-Fi / LAN)",
              "en": "Satisfaction with internet connection quality"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": true,
            "min": 1,
            "max": 5,
            "scaleGroup": "sat_5pt",
            "groupCode": "wifi",
            "showForStatus": [],
            "options": []
          },
          {
            "id": "overall_sat",
            "sectionId": "quality",
            "order": 99,
            "type": "scale",
            "label": {
              "th": "โดยภาพรวม ท่านพึงพอใจต่อสิ่งสนับสนุนการเรียนรู้ในมหาวิทยาลัยกรุงเทพแค่ไหน",
              "en": "Overall, how satisfied are you with learning support at BU"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": true,
            "min": 1,
            "max": 5,
            "scaleGroup": "sat_5pt",
            "groupCode": "overall",
            "showForStatus": [],
            "options": []
          }
        ]
      },
      {
        "id": "need",
        "order": 3,
        "title": {
          "th": "ส่วนที่ 3: สิ่งที่ต้องการให้มหาวิทยาลัยพัฒนา/เพิ่ม",
          "en": "Part 3: Areas for improvement"
        },
        "description": {
          "th": "",
          "en": ""
        },
        "questions": [
          {
            "id": "improve_multi",
            "sectionId": "need",
            "order": 1,
            "type": "checkbox",
            "label": {
              "th": "ท่านต้องการให้มหาวิทยาลัย “พัฒนา/เพิ่ม” ด้านใดบ้าง (ตอบได้มากกว่า 1 ข้อ)",
              "en": "Which areas should the university improve/add (multiple choice)"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": false,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [],
            "options": [
              {
                "value": "study_space",
                "order": 1,
                "label": {
                  "th": "พื้นที่อ่านหนังสือ/ทำงานเพิ่มขึ้น",
                  "en": "More study/work spaces"
                }
              },
              {
                "value": "cowork",
                "order": 2,
                "label": {
                  "th": "พื้นที่ทำงานกลุ่ม / Co-working Space ที่จองได้",
                  "en": "Bookable group / co-working spaces"
                }
              },
              {
                "value": "wifi",
                "order": 3,
                "label": {
                  "th": "คุณภาพอินเทอร์เน็ต / Wi-Fi",
                  "en": "Internet / Wi-Fi quality"
                }
              },
              {
                "value": "activity_space",
                "order": 4,
                "label": {
                  "th": "พื้นที่กิจกรรม / ชมรม / การแสดงผลงาน",
                  "en": "Activity / club / showcase spaces"
                }
              },
              {
                "value": "counseling",
                "order": 5,
                "label": {
                  "th": "บริการให้คำปรึกษาด้านการเรียน / การวางแผนการเรียน",
                  "en": "Academic counseling / study planning services"
                }
              },
              {
                "value": "mental_health",
                "order": 6,
                "label": {
                  "th": "บริการด้านสุขภาพจิต / การดูแลสุขภาวะนักศึกษา",
                  "en": "Mental health & wellbeing services"
                }
              },
              {
                "value": "scholarship_job",
                "order": 7,
                "label": {
                  "th": "ทุนการศึกษา / งานพิเศษ / Internship",
                  "en": "Scholarships / part-time jobs / internships"
                }
              },
              {
                "value": "digital_system",
                "order": 8,
                "label": {
                  "th": "ระบบดิจิทัลที่เกี่ยวข้องกับการเรียน (ลงทะเบียน, เกรด, LMS ฯลฯ)",
                  "en": "Digital systems for learning (registration, grades, LMS)"
                }
              },
              {
                "value": "extra_skills",
                "order": 9,
                "label": {
                  "th": "สิ่งสนับสนุนการเรียนรู้ภาษา/ทักษะเพิ่มเติม",
                  "en": "Language & extra-skill learning support"
                }
              },
              {
                "value": "other",
                "order": 99,
                "label": {
                  "th": "อื่น ๆ",
                  "en": "Other"
                }
              }
            ]
          }
        ]
      },
      {
        "id": "open",
        "order": 4,
        "title": {
          "th": "ส่วนที่ 4: ความพึงพอใจโดยรวมและข้อเสนอแนะปลายเปิด",
          "en": "Part 4: Overall satisfaction & open feedback"
        },
        "description": {
          "th": "",
          "en": ""
        },
        "questions": [
          {
            "id": "feel_best",
            "sectionId": "open",
            "order": 1,
            "type": "textarea",
            "label": {
              "th": "ด้านใดเกี่ยวกับ “สิ่งสนับสนุนการเรียนรู้” ที่ท่านรู้สึกพึงพอใจมากที่สุด เพราะเหตุใด",
              "en": "Which aspects of learning support do you like the most, and why"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": false,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [],
            "options": []
          },
          {
            "id": "need_improve_urgent",
            "sectionId": "open",
            "order": 2,
            "type": "textarea",
            "label": {
              "th": "ด้านใดเกี่ยวกับ “สิ่งสนับสนุนการเรียนรู้” ที่ท่านอยากให้ปรับปรุงเร่งด่วนที่สุด เพราะเหตุใด",
              "en": "Which aspects should be improved most urgently, and why"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": false,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [],
            "options": []
          },
          {
            "id": "life_happier",
            "sectionId": "open",
            "order": 3,
            "type": "textarea",
            "label": {
              "th": "หากจะทำให้การใช้ชีวิตและการเรียนที่ BU มีความสุขมากขึ้น อยากให้เพิ่มหรือลดอะไร",
              "en": "If BU could improve one thing to make your life & study happier, what would it be?"
            },
            "help": {
              "th": "",
              "en": ""
            },
            "required": false,
            "min": null,
            "max": null,
            "scaleGroup": "",
            "groupCode": "",
            "showForStatus": [],
            "options": []
          }
        ]
      }
    ],
    "questionsFlat": [
      {
        "id": "status",
        "sectionId": "basic",
        "order": 1,
        "type": "radio",
        "label": {
          "th": "สถานะของท่าน",
          "en": "Your status"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": true,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [],
        "options": [
          {
            "value": "STU",
            "order": 1,
            "label": {
              "th": "นักศึกษา",
              "en": "Student"
            }
          },
          {
            "value": "STAFF_BU",
            "order": 2,
            "label": {
              "th": "บุคลากรของมหาวิทยาลัย",
              "en": ""
            }
          },
          {
            "value": "PARENT",
            "order": 3,
            "label": {
              "th": "ผู้ปกครอง",
              "en": ""
            }
          },
          {
            "value": "ALUMNI",
            "order": 4,
            "label": {
              "th": "ศิษย์เก่า",
              "en": ""
            }
          },
          {
            "value": "EXTERNAL",
            "order": 5,
            "label": {
              "th": "หน่วยงานภายนอก / บุคคลภายนอก",
              "en": ""
            }
          },
          {
            "value": "OTHER",
            "order": 99,
            "label": {
              "th": "อื่น ๆ",
              "en": "Other"
            }
          }
        ]
      },
      {
        "id": "faculty_id",
        "sectionId": "basic",
        "order": 2,
        "type": "select",
        "label": {
          "th": "คณะ/วิทยาลัยของท่าน",
          "en": "Your faculty/school"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": true,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [
          "STU"
        ],
        "options": []
      },
      {
        "id": "program_id",
        "sectionId": "basic",
        "order": 3,
        "type": "select",
        "label": {
          "th": "หลักสูตร/สาขาวิชาที่ท่านกำลังศึกษา",
          "en": "Program/major you are enrolled in"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": true,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [
          "STU"
        ],
        "options": []
      },
      {
        "id": "unit_id",
        "sectionId": "basic",
        "order": 4,
        "type": "select",
        "label": {
          "th": "หน่วยงานที่ท่านสังกัด",
          "en": ""
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": true,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [
          "STAFF_BU"
        ],
        "options": []
      },
      {
        "id": "parent_detail",
        "sectionId": "basic",
        "order": 5,
        "type": "textarea",
        "label": {
          "th": "โปรดระบุความสัมพันธ์กับนักศึกษาหรือรายละเอียดเพิ่มเติม (ถ้าต้องการ)",
          "en": ""
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": false,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [
          "PARENT"
        ],
        "options": []
      },
      {
        "id": "alumni_detail",
        "sectionId": "basic",
        "order": 6,
        "type": "textarea",
        "label": {
          "th": "โปรดระบุรุ่น/ปีที่สำเร็จการศึกษา หรือรายละเอียดเพิ่มเติม (ถ้าต้องการ)",
          "en": ""
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": false,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [
          "ALUMNI"
        ],
        "options": []
      },
      {
        "id": "external_org",
        "sectionId": "basic",
        "order": 7,
        "type": "textarea",
        "label": {
          "th": "โปรดระบุชื่อหน่วยงาน/องค์กรของท่าน (ถ้าต้องการ)",
          "en": ""
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": false,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [
          "EXTERNAL"
        ],
        "options": []
      },
      {
        "id": "wifi_sat",
        "sectionId": "quality",
        "order": 2,
        "type": "scale",
        "label": {
          "th": "ระดับ “ความพึงพอใจ” ต่อคุณภาพการเชื่อมต่ออินเทอร์เน็ต (Wi-Fi / LAN)",
          "en": "Satisfaction with internet connection quality"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": true,
        "min": 1,
        "max": 5,
        "scaleGroup": "sat_5pt",
        "groupCode": "wifi",
        "showForStatus": [],
        "options": []
      },
      {
        "id": "overall_sat",
        "sectionId": "quality",
        "order": 99,
        "type": "scale",
        "label": {
          "th": "โดยภาพรวม ท่านพึงพอใจต่อสิ่งสนับสนุนการเรียนรู้ในมหาวิทยาลัยกรุงเทพแค่ไหน",
          "en": "Overall, how satisfied are you with learning support at BU"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": true,
        "min": 1,
        "max": 5,
        "scaleGroup": "sat_5pt",
        "groupCode": "overall",
        "showForStatus": [],
        "options": []
      },
      {
        "id": "improve_multi",
        "sectionId": "need",
        "order": 1,
        "type": "checkbox",
        "label": {
          "th": "ท่านต้องการให้มหาวิทยาลัย “พัฒนา/เพิ่ม” ด้านใดบ้าง (ตอบได้มากกว่า 1 ข้อ)",
          "en": "Which areas should the university improve/add (multiple choice)"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": false,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [],
        "options": [
          {
            "value": "study_space",
            "order": 1,
            "label": {
              "th": "พื้นที่อ่านหนังสือ/ทำงานเพิ่มขึ้น",
              "en": "More study/work spaces"
            }
          },
          {
            "value": "cowork",
            "order": 2,
            "label": {
              "th": "พื้นที่ทำงานกลุ่ม / Co-working Space ที่จองได้",
              "en": "Bookable group / co-working spaces"
            }
          },
          {
            "value": "wifi",
            "order": 3,
            "label": {
              "th": "คุณภาพอินเทอร์เน็ต / Wi-Fi",
              "en": "Internet / Wi-Fi quality"
            }
          },
          {
            "value": "activity_space",
            "order": 4,
            "label": {
              "th": "พื้นที่กิจกรรม / ชมรม / การแสดงผลงาน",
              "en": "Activity / club / showcase spaces"
            }
          },
          {
            "value": "counseling",
            "order": 5,
            "label": {
              "th": "บริการให้คำปรึกษาด้านการเรียน / การวางแผนการเรียน",
              "en": "Academic counseling / study planning services"
            }
          },
          {
            "value": "mental_health",
            "order": 6,
            "label": {
              "th": "บริการด้านสุขภาพจิต / การดูแลสุขภาวะนักศึกษา",
              "en": "Mental health & wellbeing services"
            }
          },
          {
            "value": "scholarship_job",
            "order": 7,
            "label": {
              "th": "ทุนการศึกษา / งานพิเศษ / Internship",
              "en": "Scholarships / part-time jobs / internships"
            }
          },
          {
            "value": "digital_system",
            "order": 8,
            "label": {
              "th": "ระบบดิจิทัลที่เกี่ยวข้องกับการเรียน (ลงทะเบียน, เกรด, LMS ฯลฯ)",
              "en": "Digital systems for learning (registration, grades, LMS)"
            }
          },
          {
            "value": "extra_skills",
            "order": 9,
            "label": {
              "th": "สิ่งสนับสนุนการเรียนรู้ภาษา/ทักษะเพิ่มเติม",
              "en": "Language & extra-skill learning support"
            }
          },
          {
            "value": "other",
            "order": 99,
            "label": {
              "th": "อื่น ๆ",
              "en": "Other"
            }
          }
        ]
      },
      {
        "id": "feel_best",
        "sectionId": "open",
        "order": 1,
        "type": "textarea",
        "label": {
          "th": "ด้านใดเกี่ยวกับ “สิ่งสนับสนุนการเรียนรู้” ที่ท่านรู้สึกพึงพอใจมากที่สุด เพราะเหตุใด",
          "en": "Which aspects of learning support do you like the most, and why"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": false,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [],
        "options": []
      },
      {
        "id": "need_improve_urgent",
        "sectionId": "open",
        "order": 2,
        "type": "textarea",
        "label": {
          "th": "ด้านใดเกี่ยวกับ “สิ่งสนับสนุนการเรียนรู้” ที่ท่านอยากให้ปรับปรุงเร่งด่วนที่สุด เพราะเหตุใด",
          "en": "Which aspects should be improved most urgently, and why"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": false,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [],
        "options": []
      },
      {
        "id": "life_happier",
        "sectionId": "open",
        "order": 3,
        "type": "textarea",
        "label": {
          "th": "หากจะทำให้การใช้ชีวิตและการเรียนที่ BU มีความสุขมากขึ้น อยากให้เพิ่มหรือลดอะไร",
          "en": "If BU could improve one thing to make your life & study happier, what would it be?"
        },
        "help": {
          "th": "",
          "en": ""
        },
        "required": false,
        "min": null,
        "max": null,
        "scaleGroup": "",
        "groupCode": "",
        "showForStatus": [],
        "options": []
      }
    ],
    "lookups": {
      "faculties": [
        {
          "id": "AC",
          "name": {
            "th": "คณะบัญชี",
            "en": "School of Accounting"
          },
          "order": 1
        },
        {
          "id": "BA",
          "name": {
            "th": "คณะบริหารธุรกิจ",
            "en": "School of Business Administration"
          },
          "order": 2
        },
        {
          "id": "CA",
          "name": {
            "th": "คณะนิเทศศาสตร์",
            "en": "School of Communication Arts"
          },
          "order": 3
        },
        {
          "id": "LA",
          "name": {
            "th": "คณะนิติศาสตร์",
            "en": "School of Law"
          },
          "order": 4
        },
        {
          "id": "HM",
          "name": {
            "th": "คณะมนุษยศาสตร์และการจัดการการท่องเที่ยว",
            "en": "School of Humanities and Tourism Management"
          },
          "order": 5
        },
        {
          "id": "EC",
          "name": {
            "th": "คณะเศรษฐศาสตร์และการลงทุน",
            "en": "School of Economics and Investment"
          },
          "order": 6
        },
        {
          "id": "ITI",
          "name": {
            "th": "คณะเทคโนโลยีสารสนเทศและนวัตกรรม",
            "en": "School of Information Technology and Innovation"
          },
          "order": 7
        },
        {
          "id": "FA",
          "name": {
            "th": "คณะศิลปกรรมศาสตร์",
            "en": "School of Fine and Applied Arts"
          },
          "order": 8
        },
        {
          "id": "EE",
          "name": {
            "th": "คณะวิศวกรรมศาสตร์",
            "en": "School of Engineering"
          },
          "order": 9
        },
        {
          "id": "BUI",
          "name": {
            "th": "วิทยาลัยนานาชาติ",
            "en": "Bangkok University International (BUI)"
          },
          "order": 10
        },
        {
          "id": "ARC",
          "name": {
            "th": "คณะสถาปัตยกรรมศาสตร์",
            "en": "School of Architecture"
          },
          "order": 11
        },
        {
          "id": "SEM",
          "name": {
            "th": "คณะการสร้างเจ้าของธุรกิจและการบริหารกิจการ(SEM)",
            "en": "School of Entrepreneurship and Management"
          },
          "order": 12
        },
        {
          "id": "DC",
          "name": {
            "th": "คณะดิจิทัลมีเดียและศิลปะภาพยนตร์",
            "en": "School of Digital Media and Cinematic Arts"
          },
          "order": 13
        },
        {
          "id": "BUCI",
          "name": {
            "th": "วิทยาลัยนานาชาติจีน",
            "en": "Bangkok University Chinese International (BUCI)"
          },
          "order": 14
        },
        {
          "id": "GRAD",
          "name": {
            "th": "บัณฑิตวิทยาลัย",
            "en": "Graduate School"
          },
          "order": 15
        }
      ],
      "programsByFaculty": {
        "AC": [
          {
            "id": "AC_ALL",
            "type": "faculty_only",
            "majorName": {
              "th": "คณะบัญชี",
              "en": ""
            },
            "display": {
              "th": "คณะบัญชี",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          }
        ],
        "BA": [
          {
            "id": "BA_MKT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการตลาด",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการตลาด",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "BA_FIN",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการเงิน",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการเงิน",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 2
          },
          {
            "id": "BA_MGMT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการจัดการ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการจัดการ",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 3
          },
          {
            "id": "BA_IB",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการจัดการธุรกิจระหว่างประเทศ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการจัดการธุรกิจระหว่างประเทศ",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 4
          },
          {
            "id": "BA_LOG",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการจัดการโลจิสติกส์และโซ่อุปทาน",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการจัดการโลจิสติกส์และโซ่อุปทาน",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 5
          },
          {
            "id": "BA_DMKT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการตลาดดิจิทัล",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการตลาดดิจิทัล",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 6
          },
          {
            "id": "BA_FP",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการวางแผนการเงินและการลงทุน",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการวางแผนการเงินและการลงทุน",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 7
          }
        ],
        "CA": [
          {
            "id": "CA_RADIO",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาวิทยุกระจายเสียง วิทยุโทรทัศน์ และ การผลิตสื่อสตรีมมิ่ง",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาวิทยุกระจายเสียง วิทยุโทรทัศน์ และ การผลิตสื่อสตรีมมิ่ง",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "CA_CONTENT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการผลิตเนื้อหาสร้างสรรค์และประสบการณ์ดิจิทัล",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการผลิตเนื้อหาสร้างสรรค์และประสบการณ์ดิจิทัล",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 2
          },
          {
            "id": "CA_NEWMD",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการสื่อสารและสื่อใหม่",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการสื่อสารและสื่อใหม่",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 3
          },
          {
            "id": "CA_PERF",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาศิลปะการแสดง",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาศิลปะการแสดง",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 4
          },
          {
            "id": "CA_EVENT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการผลิตอีเว้นท์ และการจัดการนิทรรศการและการประชุม",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการผลิตอีเว้นท์ และการจัดการนิทรรศการและการประชุม",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 5
          },
          {
            "id": "CA_INNO_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการผลิตสื่อนวัตกรรม(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการผลิตสื่อนวัตกรรม(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 6
          }
        ],
        "LA": [
          {
            "id": "LA_ALL",
            "type": "faculty_only",
            "majorName": {
              "th": "คณะนิติศาสตร์",
              "en": ""
            },
            "display": {
              "th": "คณะนิติศาสตร์",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          }
        ],
        "HM": [
          {
            "id": "HM_ENG",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาภาษาอังกฤษ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาภาษาอังกฤษ",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "HM_HOTEL",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการจัดการการโรงแรม",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการจัดการการโรงแรม",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 2
          },
          {
            "id": "HM_TOUR",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการจัดการการท่องเที่ยวและเรือสำราญ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการจัดการการท่องเที่ยวและเรือสำราญ",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 3
          },
          {
            "id": "HM_AIRBIZ",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการจัดการธุรกิจสายการบิน",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการจัดการธุรกิจสายการบิน",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 4
          },
          {
            "id": "HM_CULART_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาศิลปะการประกอบและออกแบบอาหาร(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาศิลปะการประกอบและออกแบบอาหาร(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 5
          }
        ],
        "EC": [
          {
            "id": "EC_ALL",
            "type": "faculty_only",
            "majorName": {
              "th": "คณะเศรษฐศาสตร์และการลงทุน",
              "en": ""
            },
            "display": {
              "th": "คณะเศรษฐศาสตร์และการลงทุน",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          }
        ],
        "ITI": [
          {
            "id": "ITI_CS",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาวิทยาการคอมพิวเตอร์",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาวิทยาการคอมพิวเตอร์",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "ITI_IT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาเทคโนโลยีสารสนเทศ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาเทคโนโลยีสารสนเทศ",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 2
          },
          {
            "id": "ITI_GAME",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาเกมและสื่อเชิงโต้ตอบ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาเกมและสื่อเชิงโต้ตอบ",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 3
          }
        ],
        "FA": [
          {
            "id": "FA_VCD",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการออกแบบนิเทศศิลป์",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการออกแบบนิเทศศิลป์",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "FA_FASHION",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการออกแบบแฟชั่น",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการออกแบบแฟชั่น",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 2
          },
          {
            "id": "FA_ARTDES",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาศิลปะและการออกแบบ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาศิลปะและการออกแบบ",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 3
          }
        ],
        "EE": [
          {
            "id": "EE_EE",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาวิศวกรรมไฟฟ้า",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาวิศวกรรมไฟฟ้า",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "EE_CE_ROBO",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาวิศวกรรมคอมพิวเตอร์และหุ่นยนต์",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาวิศวกรรมคอมพิวเตอร์และหุ่นยนต์",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 2
          },
          {
            "id": "EE_MM",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาวิศวกรรมมัลติมีเดียและเอ็นเตอร์เทนเมนต์",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาวิศวกรรมมัลติมีเดียและเอ็นเตอร์เทนเมนต์",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 3
          },
          {
            "id": "EE_AI_DATA",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาวิศวกรรมปัญญาประดิษฐ์และวิทยาการข้อมูล",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาวิศวกรรมปัญญาประดิษฐ์และวิทยาการข้อมูล",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 4
          }
        ],
        "ARC": [
          {
            "id": "ARC_ARCH5",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาสถาปัตยกรรม หลักสูตร 5 ปี*",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาสถาปัตยกรรม หลักสูตร 5 ปี*",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "ARC_INARCH",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาสถาปัตยกรรมภายใน",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาสถาปัตยกรรมภายใน",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 2
          }
        ],
        "SEM": [
          {
            "id": "SEM_OWNER_TH",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการเป็นเจ้าของธุรกิจ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการเป็นเจ้าของธุรกิจ",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "SEM_OWNER_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการเป็นเจ้าของธุรกิจ   (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการเป็นเจ้าของธุรกิจ   (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 2
          },
          {
            "id": "SEM_AI_ENT_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาวิศวกรรมปัญญาประดิษฐ์และการเป็นผู้ประกอบการ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาวิศวกรรมปัญญาประดิษฐ์และการเป็นผู้ประกอบการ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 3
          }
        ],
        "DC": [
          {
            "id": "DC_MEDIA",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาสื่อดิจิทัล",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาสื่อดิจิทัล",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "DC_FILM",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาภาพยนตร์",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาภาพยนตร์",
              "en": ""
            },
            "level": "UG",
            "isInternational": false,
            "order": 2
          },
          {
            "id": "DC_FILMBIZ_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการผลิตและธุรกิจภาพยนตร์ ซีรีส์ และเนื้อหาสากล (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการผลิตและธุรกิจภาพยนตร์ ซีรีส์ และเนื้อหาสากล (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 3
          }
        ],
        "BUCI": [
          {
            "id": "BUCI_BCHN",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาภาษาจีนธุรกิจ",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาภาษาจีนธุรกิจ",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 1
          }
        ],
        "BUI": [
          {
            "id": "BUI_MKT_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการตลาด (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการตลาด (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 1
          },
          {
            "id": "BUI_BENG_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาภาษาอังกฤษธุรกิจ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาภาษาอังกฤษธุรกิจ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 2
          },
          {
            "id": "BUI_TOUR_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการจัดการท่องเที่ยวและการบริการนานาชาติ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการจัดการท่องเที่ยวและการบริการนานาชาติ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 3
          },
          {
            "id": "BUI_VCD_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาการออกแบบนิเทศศิลป์เชิงสร้างสรรค์ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาการออกแบบนิเทศศิลป์เชิงสร้างสรรค์ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 4
          },
          {
            "id": "BUI_COMM_INT",
            "type": "major",
            "majorName": {
              "th": "สาขาวิชาสื่อและการสื่อสาร (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "สาขาวิชาสื่อและการสื่อสาร (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 5
          },
          {
            "id": "BUI_BBA_INT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรบริหารธุรกิจบัณฑิต",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรบริหารธุรกิจบัณฑิต",
              "en": ""
            },
            "level": "UG",
            "isInternational": true,
            "order": 6
          }
        ],
        "GRAD": [
          {
            "id": "GRAD_MBA_TH",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 1
          },
          {
            "id": "GRAD_MBA_EN",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต - (หลักสูตรภาษาอังกฤษ)",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต - (หลักสูตรภาษาอังกฤษ)",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": true,
            "order": 2
          },
          {
            "id": "GRAD_MCOMM_DMKT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรนิเทศศาสตรมหาบัณฑิต - สาขาวิชาการสื่อสารการตลาดดิจิทัล",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรนิเทศศาสตรมหาบัณฑิต - สาขาวิชาการสื่อสารการตลาดดิจิทัล",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 3
          },
          {
            "id": "GRAD_MCOMM_BRAND",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรนิเทศศาสตรมหาบัณฑิต - สาขาวิชาการบริหารแบรนด์และการสื่อสารเชิงกลยุทธ์",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรนิเทศศาสตรมหาบัณฑิต - สาขาวิชาการบริหารแบรนด์และการสื่อสารเชิงกลยุทธ์",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 4
          },
          {
            "id": "GRAD_MCOMM_INT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรนิเทศศาสตรมหาบัณฑิต - สาขาวิชาการสื่อสารสากล(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรนิเทศศาสตรมหาบัณฑิต - สาขาวิชาการสื่อสารสากล(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": true,
            "order": 5
          },
          {
            "id": "GRAD_MLAW",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรนิติศาสตรมหาบัณฑิต",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรนิติศาสตรมหาบัณฑิต",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 6
          },
          {
            "id": "GRAD_MARCH",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรสถาปัตยกรรมศาสตรมหาบัณฑิต",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรสถาปัตยกรรมศาสตรมหาบัณฑิต",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 7
          },
          {
            "id": "GRAD_MS_ITDATA",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต - สาขาวิชาเทคโนโลยีสารสนเทศและวิทยาการข้อมูล",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรวิทยาศาสตรมหาบัณฑิต - สาขาวิชาเทคโนโลยีสารสนเทศและวิทยาการข้อมูล",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 8
          },
          {
            "id": "GRAD_MA_TOUR",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรศิลปศาสตรมหาบัณฑิต - สาขาวิชานวัตกรรมการจัดการการท่องเที่ยวและการบริการ",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรศิลปศาสตรมหาบัณฑิต - สาขาวิชานวัตกรรมการจัดการการท่องเที่ยวและการบริการ",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 9
          },
          {
            "id": "GRAD_MM_ENT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรการจัดการมหาบัณฑิต - สาขาวิชาความเป็นผู้ประกอบการ",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรการจัดการมหาบัณฑิต - สาขาวิชาความเป็นผู้ประกอบการ",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 10
          },
          {
            "id": "GRAD_MBA_INNO_INT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต - สาขาวิชาการจัดการนวัตกรรม (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต - สาขาวิชาการจัดการนวัตกรรม (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": true,
            "order": 11
          },
          {
            "id": "GRAD_MENG_EECS_INT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต - สาขาวิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต - สาขาวิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": true,
            "order": 12
          },
          {
            "id": "GRAD_MBA_ONLINE",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต - (หลักสูตรการจัดการศึกษาผ่านระบบเทคโนโลยีสารสนเทศ)",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรบริหารธุรกิจมหาบัณฑิต - (หลักสูตรการจัดการศึกษาผ่านระบบเทคโนโลยีสารสนเทศ)",
              "en": ""
            },
            "level": "GRAD",
            "isInternational": false,
            "order": 13
          },
          {
            "id": "GRAD_DCOMM_INT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรนิเทศศาสตรดุษฎีบัณฑิต - สาขาวิชาการสื่อสารสากล(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรนิเทศศาสตรดุษฎีบัณฑิต - สาขาวิชาการสื่อสารสากล(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "PHD",
            "isInternational": true,
            "order": 14
          },
          {
            "id": "GRAD_DCOMM_BRAND",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรนิเทศศาสตรดุษฎีบัณฑิต - สาขาวิชาการบริหารแบรนด์และการสื่อสารเชิงกลยุทธ์",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรนิเทศศาสตรดุษฎีบัณฑิต - สาขาวิชาการบริหารแบรนด์และการสื่อสารเชิงกลยุทธ์",
              "en": ""
            },
            "level": "PHD",
            "isInternational": false,
            "order": 15
          },
          {
            "id": "GRAD_DPHIL_KM_INT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรปรัชญาดุษฎีบัณฑิต - สาขาวิชาการจัดการความรู้และนวัตกรรม(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรปรัชญาดุษฎีบัณฑิต - สาขาวิชาการจัดการความรู้และนวัตกรรม(หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "PHD",
            "isInternational": true,
            "order": 16
          },
          {
            "id": "GRAD_DENG_EECS_INT",
            "type": "major",
            "majorName": {
              "th": "หลักสูตรวิศวกรรมศาสตรดุษฎีบัณฑิต - สาขาวิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "display": {
              "th": "หลักสูตรวิศวกรรมศาสตรดุษฎีบัณฑิต - สาขาวิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์ (หลักสูตรนานาชาติ)",
              "en": ""
            },
            "level": "PHD",
            "isInternational": true,
            "order": 17
          }
        ]
      },
      "units": [
        {
          "id": "OSS",
          "name": {
            "th": "หน่วยบริการเบ็ดเสร็จ",
            "en": ""
          },
          "group": "SUPPORT",
          "order": 1
        },
        {
          "id": "SCH",
          "name": {
            "th": "แผนกทุนการศึกษา",
            "en": ""
          },
          "group": "SUPPORT",
          "order": 2
        },
        {
          "id": "LIB",
          "name": {
            "th": "สำนักหอสมุดและพื้นที่การเรียนรู้",
            "en": ""
          },
          "group": "SUPPORT",
          "order": 3
        },
        {
          "id": "REG",
          "name": {
            "th": "งานทะเบียน",
            "en": ""
          },
          "group": "ACADEMIC",
          "order": 10
        }
      ]
    }
  }
};
